name: pahkat-prefix-cli

on:
  push: {}

env:
  RUST_VERSION: stable
  CARGO_INCREMENTAL: 0
  RUSTUP_MAX_RETRIES: 10
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: full

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Divvun CI
      uses: divvun/actions/setup@master
      with:
        key: ${{ secrets.DIVVUN_KEY }}
    - name: Get version
      id: version
      uses: divvun/actions/version@master
      with:
        cargo: pahkat-cli/Cargo.toml
        nightly: master, develop
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install build dependencies
      uses: divvun/actions/pahkat/init@master
      with:
        repo: https://pahkat.uit.no/devtools/
        channel: nightly
        packages: pahkat-uploader
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: rustfmt
        target: i686-pc-windows-msvc
    - name: Build pahkat-prefix-cli
      run: |
        cd pahkat-cli
        cargo check --features prefix
        cargo build --features prefix --release --target i686-pc-windows-msvc
        cd ..
      env:
        RUSTC_BOOTSTRAP: 1
    - name: Create dist
      run: |
        mkdir -p dist/bin
        mv target/i686-pc-windows-msvc/release/pahkat-cli.exe dist/bin/pahkat-prefix.exe
    - name: Sign code
      uses: divvun/actions/codesign@master
      with:
        path: dist/bin/pahkat-prefix.exe
    - name: Create tarball package
      id: installer
      uses: divvun/actions/create-txz@master
      with:
        path: dist
    - name: Deploy
      uses: divvun/actions/deploy@master
      with:
        package-id: pahkat-prefix-cli
        type: TarballPackage
        platform: windows
        arch: i686
        version: ${{ steps.version.outputs.version }}
        payload-path: ${{ steps.installer.outputs['txz-path'] }}
        repo: https://pahkat.thetc.se/devtools/
        channel: ${{ steps.version.outputs.channel }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-macos:
    runs-on: macOS-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Divvun CI
      uses: divvun/actions/setup@master
      with:
        key: ${{ secrets.DIVVUN_KEY }}
    - name: Get version
      id: version
      uses: divvun/actions/version@master
      with:
        cargo: pahkat-cli/Cargo.toml
        nightly: master, develop
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install build dependencies
      uses: divvun/actions/pahkat/init@master
      with:
        repo: https://pahkat.uit.no/devtools/
        channel: nightly
        packages: pahkat-uploader
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        components: rustfmt
        override: true
    - name: Build pahkat-prefix-cli
      run: |
        cd pahkat-cli
        cargo check --features prefix
        cargo build --features prefix --release
        cd ..
    - name: Create dist
      run: |
        strip target/release/pahkat-cli
        mkdir -p dist/bin
        mv target/release/pahkat-cli dist/bin/pahkat-prefix
    - name: Sign code
      uses: divvun/actions/codesign@master
      with:
        path: dist/bin/pahkat-prefix
    - name: Create tarball package
      id: installer
      uses: divvun/actions/create-txz@master
      with:
        path: dist
    - name: Deploy
      uses: divvun/actions/deploy@master
      with:
        package-id: pahkat-prefix-cli
        type: TarballPackage
        platform: macos
        arch: x86_64
        version: ${{ steps.version.outputs.version }}
        payload-path: ${{ steps.installer.outputs['txz-path'] }}
        repo: https://pahkat.thetc.se/devtools/
        channel: ${{ steps.version.outputs.channel }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Divvun CI
      uses: divvun/actions/setup@master
      with:
        key: ${{ secrets.DIVVUN_KEY }}
    - name: Get version
      id: version
      uses: divvun/actions/version@master
      with:
        cargo: pahkat-cli/Cargo.toml
        nightly: master, develop
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install musl libs and tools
      run: |
        sudo apt install -y musl musl-tools
    - name: Install build dependencies
      uses: divvun/actions/pahkat/init@master
      with:
        repo: https://pahkat.uit.no/devtools/
        channel: nightly
        packages: pahkat-uploader
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-musl
        profile: minimal
        components: rustfmt
        override: true
    - name: Build pahkat-prefix-cli
      run: |
        cd pahkat-cli
        cargo check --features prefix
        cargo build --features prefix --release
        cd ..
    - name: Create dist
      run: |
        strip target/release/pahkat-cli
        mkdir -p dist/bin
        mv target/release/pahkat-cli dist/bin/pahkat-prefix
    - name: Create tarball package
      id: installer
      uses: divvun/actions/create-txz@master
      with:
        path: dist
    - name: Deploy
      uses: divvun/actions/deploy@master
      with:
        package-id: pahkat-prefix-cli
        type: TarballPackage
        platform: linux
        arch: x86_64
        version: ${{ steps.version.outputs.version }}
        payload-path: ${{ steps.installer.outputs['txz-path'] }}
        repo: https://pahkat.thetc.se/devtools/
        channel: ${{ steps.version.outputs.channel }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
